---
title: "ASHRAE Energy Prediction"
output: html_notebook
---

## Reading in data files

```{r, message = FALSE}

library(tidyverse)

building <- read_csv("building_metadata.csv")

weather_train <- read_csv("weather_train.csv")

weather_test <- read_csv("weather_test.csv")

train <- read_csv("train.csv")

test <- read_csv("test.csv")

```

## Prepare the training dataset

```{r}

training_dataset <- train %>%
  left_join(building, by = "building_id")

training_dataset <- training_dataset %>%
  left_join(weather_train, by = c("site_id", "timestamp"))
  
```
## Prepare the testing dataset

```{r}
testing_dataset <- test %>%
  left_join(building, by = "building_id")

testing_dataset <- testing_dataset %>%
  left_join(weather_test, by = c("site_id", "timestamp"))
```

## Examine the training dataset

```{r}
dim(training_dataset)
summary(training_dataset)
```
## Examine the test dataset

```{r}
dim(testing_dataset)
summary(testing_dataset)
```
## Aggregate data by day and meter type
```{r}
training_dataset$date <- as.Date(training_dataset$timestamp)


daily_data <- training_dataset %>%
  group_by(date, meter) %>%
  summarise(air_temperature = mean(air_temperature, na.rm = TRUE),
            cloud_coverage = mean(cloud_coverage, na.rm = TRUE),
            dew_temperature = mean(dew_temperature, na.rm = TRUE),
            precip_depth_1_hr = mean(precip_depth_1_hr, na.rm = TRUE),
            sea_level_pressure = mean(sea_level_pressure, na.rm = TRUE),
            wind_direction = mean(wind_direction, na.rm = TRUE),
            wind_speed = mean(wind_speed, na.rm = TRUE),
            square_feet = mean(square_feet, na.rm = TRUE),
            year_built = max(year_built, na.rm = TRUE),
            floor_count = max(floor_count, na.rm = TRUE),
            meter_reading = mean(meter_reading, na.rm = TRUE))
```
## Examine scatterplots

```{r}
library(BioStatR)
pairs(daily_data, diag.panel = panel.hist, lower.panel = panel.smooth , upper.panel = NULL)
```

```{r}
pos = c(3:13)
numeric <- daily_data [, pos]   
summary(numeric)
round(cor(numeric), 2)
 ```


